# Generated by Django 3.1.3 on 2020-11-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osn', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priloshenie',
            name='Pub_Date',
        ),
        migrations.AddField(
            model_name='priloshenie',
            name='Linker',
            field=models.TextField(default='dkkdkfjf', verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priloshenie',
            name='Price',
            field=models.FloatField(default=4, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priloshenie',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='images/blog/%Y/%m/%d', verbose_name='Ссылка картинки'),
        ),
    ]
